### ISSUE TITLE
Device registration like a plugin

### ISSUE THREAD

**Issue by scr34m** [py60800/tuya#2]
I'm working to attach my tuya based devices to Homekit and with yours package it is do able, but instand to extend yours code base with devices i thunk it is better to have a plugin like solution to register a device.

A few modifications made in my fork https://github.com/scr34m/tuya (with a code style update as well) so now I can keep my device code separated from the package, and of course needed to merge @Blaok https://github.com/Blaok/tuya code too work with 3.3 version. Of course need's to be cleaned up and maybe not perfect the code at the moment.

What do you think to merge later these kind of changes?

PS.: I found you code after a lot of trial and error but at least I know how the tuya communication works with the devices.

**Comment by py60800** [comment]
Hi, you may have noticed that I'm not very active right now.
Actually, I do not use anymore tuya devices so I'm not able to test any piece of code.

If any one is ready to take the lead, I am ready to redirect my page to this person.

**Comment by scr34m** [comment]
Thanks for the reply, this code was so good to start me after a lot of struggling, so until someone take the lead I work in my fork, at least this ticket will preserver the conversation.

Have a nice hooliday! 🎄
